apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: access-k8s
  namespace: teleport
# NB most of this file is copied from the pre-installed 'access' role
#  => however, that role appears not to be overwriteable.
spec:
  allow:
    kubernetes_groups:
    - '{{internal.kubernetes_groups}}'
    - system:masters      # this is bespoke
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: '*'
      name: '*'
      namespace: '*'
      verbs:
      - '*'
    kubernetes_users:
    - '{{internal.kubernetes_users}}'
    logins:
    - '{{internal.logins}}'
    - root        # this is bespoke
    node_labels:
      '*': '*'
    rules:
    - resources:
      - event
      verbs:
      - list
      - read
    - resources:
      - session
      verbs:
      - read
      - list
      where: contains(session.participants, user.metadata.name)
    - resources:
      - instance
      verbs:
      - list
      - read
    - resources:
      - cluster_maintenance_config
      verbs:
      - list
      - read
