apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - saml.yaml
  - tag.yaml
patches:
  - path: tag-values.yaml
    target:
      kind: HelmRelease
      name: teleport-access-graph