---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teleport
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./scaleway-k8s/flux-config/teleport/production/
  prune: true
  wait: true
  timeout: 5m0s
