---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    scaleway:
      region: ${ region }
      projectId: ${ project_id }
      accessKey:
        secretRef:
          namespace: kube-system
          name: scaleway-credentials
          key: SCW_ACCESS_KEY
      secretKey:
        secretRef:
          namespace: kube-system
          name: scaleway-credentials
          key: SCW_SECRET_KEY
