---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: kube-system
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: scaleway
  namespace: kube-system
spec:
  interval: 24h
  url: https://helm.scw.cloud/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scaleway-certmanager-webhook
  namespace: kube-system
spec:
  interval: 30m
  dependsOn:
  - name: cert-manager
  chart:
    spec:
      chart: scaleway-certmanager-webhook
      version: "0.3.0"
      sourceRef:
        kind: HelmRepository
        name: scaleway
        namespace: kube-system
      interval: 12h
