---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: kube-system
spec:
  provider:
    scaleway:
      region:
        secretRef:
          name: scaleway-credentials
          key: SCW_REGION
      projectId:
        secretRef:
          name: scaleway-credentials
          key: SCW_PROJECT_ID
      accessKey:
        secretRef:
          name: scaleway-credentials
          key: SCW_ACCESS_KEY
      secretKey:
        secretRef:
          name: scaleway-credentials
          key: SCW_SECRET_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: teleport-license
    namespace: default
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    target:
        name: teleport-license-external
        creationPolicy: Owner
    data:
      - secretKey: license.pem
        remoteRef:
          key: path:/teleport-demo/license/teleport-license
          version: latest_enabled
