---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1" # TODO add ^
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: kube-system
      interval: 12h
  values:
    controller:
      config:
        use-proxy-protocol: true
      service:
        annotations:
          service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: true
        externalTrafficPolicy: Local
