---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1" # TODO add ^
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: kube-system
      interval: 12h
  values:
    controller:
      config:
        use-proxy-protocol: true
      service:
        annotations:
          service.beta.kubernetes.io/scw-loadbalancer-proxy-protocol-v2: true
          # service.beta.kubernetes.io/scw-loadbalancer-zone: PAR-2 # TODO remove?
          # service.beta.kubernetes.io/scw-loadbalancer-use-hostname: true
        externalTrafficPolicy: Local

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - image: nginx
#         name: nginx
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
#   annotations:
#     external-dns.alpha.kubernetes.io/hostname: teleport.thinkahead.dev
# spec:
#   selector:
#     app: nginx
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80