---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: teleport-access-graph-ca
    namespace: teleport
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: ClusterSecretStore
        name: secret-store
    target:
        name: teleport-access-graph-ca
        creationPolicy: Owner
    data:
      - secretKey: ca.pem
        remoteRef:
          key: path:/teleport-demo/certificates/ca/cert
          version: latest_enabled