apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: teleport-on-prem@think-ahead.tech
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: issuer-account-key
    # Add a single challenge solver, HTTP01
    # solvers:
    #   - http01:
    #       ingress:
    #         class: nginx
    solvers:
    - dns01:
        webhook:
          groupName: acme.scaleway.com
          solverName: scaleway
          config:
            accessKeySecretRef:
              key: SCW_ACCESS_KEY
              name: scaleway-credentials
              namespace: cert-manager
            secretKeySecretRef:
              key: SCW_SECRET_KEY
              name: scaleway-credentials
              namespace: cert-manager