apiVersion: v1
kind: Namespace
metadata:
  name: teleport
  labels:
      pod-security.kubernetes.io/enforce: baseline
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: teleport-license
    namespace: teleport
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: ClusterSecretStore
        name: secret-store
    target:
        name: license
        creationPolicy: Owner
    data:
      - secretKey: license.pem
        remoteRef:
          key: path:/teleport-demo/license/teleport-license
          version: latest_enabled
