# More info: https://github.dev/gravitational/teleport/blob/4160786a3e6fabd9b0dcd54354820b222a22535b/examples/chart/teleport-cluster/values.yaml

clusterName: teleport.thinkahead.dev
proxyProtocol: "off"
proxyListenerMode: multiplex
enterprise: true
highAvailability:
  certManager:
    enabled: true
    issuerName: letsencrypt-prod
    issuerKind: ClusterIssuer
ingress:
  enabled: "true"
  suppressAutomaticWildcards: true  # TODO doesn't appear to work
  spec:
    ingressClassName: nginx
service:
  type: ClusterIP
annotations:
  ingress:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS